#!/usr/bin/env bash

if ! which license-checker &>/dev/null; then
    npm install -g license-checker
fi

license-checker --direct --production --csv | sed 's/@[^@"]\+"/"/' | sed 's/","/\t/g' | sed 's,",,g' >> /tmp/nodejs-inventory.csv
